@startuml Application use cases diagram
title Admin's sequence diagram: Read billing, transaction from Customer

actor Admin
participant Server
database Database_Customers as DBofC
database Database_Billing_Transaction as DBofBT


Admin -> Server : GET/customers/{ID}/transactions(or billing) with (token(JWT))
Server -> Server: validate token and authorities of admin
Server -[#red]> Admin: response : invalid token / authorities
note over Server : continue if right
Server -> DBofC : query customer by ID
DBofC -> DBofBT : relate to find transaction or billing
DBofBT -> Server : return needed transaction / billing 
Server -> Admin : response(200, data of transaction/billing list)



