@startuml Application use cases diagram
title Customer's sequence diagram : Login



actor Customer
participant Server


Customer -> Server : POST/login with email and password
Server -> Server : validate the username & password
Server -> Customer : Return Token (JWT) and information if valid login
Customer <-- Customer : Save Token in storage (SessionStorage, LocalStorage,...)

