@startuml Application use cases diagram
title Customer's sequence diagram : Logout



actor Customer
participant Server

Customer -> Server : POST/logout with Token/JWT 
Server -> Server : validate Token and update db
Server -> Customer : response(200, OK)
Customer <-- Customer : remove data, record, token,...