@startuml Application use cases diagram
skinparam actorStyle awesome
title Customer's sequence diagram : Reading Agency's information


actor Customer
participant Server
database Database_Agencies as DB

Customer -> Server : GET/agencies/{ID}
Server -> DB: query data of agency in database
DB -> Server : return data(personal information, product,...) of Agency
Server -> Customer : response with Agency's information


