@startuml Application use cases diagram
title Customer's sequence diagram : Read transaction, billing linked with product


actor Customer
participant Server
database Database_products as DB

Customer -> Server : POST with Token (JWT)
Server -> Server : validate JWT (expiration time, signature, ...)
Server -> Customer: return response (statuscode, messages,...)
Customer <- Customer : validate response
Customer <[#Red]- Customer: if JWT is not valid,\nrequire to login again and \nremove JWT
Customer -[#0000FF]> Server : if JWT is valid, \nGET/agencies/{ID}/products/{ID}
Server ->  DB : query object with ID in database
DB -> Server : information(transaction, billing,...) of product 
Server -> Customer : information(transaction, billing,...) of product 