@startuml Application use cases diagram
skinparam actorStyle awesome
title UML of E-Commercial Platform


class Information{
    name: String
    address: String
    phoneNumber: String
    gender: String
    email: String
}

class Billing{
    date: String
    by : String
}


class Transaction{
    date: String
}

class Product{
    id : String
    name: String
    transactionList: Transaction[]
    billingList: Billing[]
    price: Number
    by : Agency
}

class Customer{
    ..property..
    id : String
    information: Information
    cartList : Product[]
    transactionList: Transaction[]
    billingList: Billing[]
    ..method..
}

class Agency{
    ..property..
    information: Information
    productList : Product[]
    transaction: Transaction[]
    billing: Billing[]
    ..method..
}

class Admin{
    ..property..
    ..method..
    readAgency() : void
    createAgency(): void
    updateAgency(): void
    deleteAgency():void
}

Customer "1"*-- "1" Information 
Agency "1"*-- "many" Information
Admin "manage" -- Agency
Customer "1" *-- "many" Billing
Customer "1" *-- "many" Transaction
Agency "1" *-- "many" Product
Agency "1" *-- "many" Billing
Agency "1" *-- "many" Transaction
Product "1" -- "1" Transaction
Product "1" -- "1" Billing



@enduml