@startuml Application use cases diagram
skinparam actorStyle awesome
title UML of E-Commercial Platform


class Infomation{
    name: String
    address: String
    phoneNumber: String
    gender: String
    email: String
}

class Customer{
    ..property..
    information: Infomation
    cart :
    transaction:
    billing:
    ..method..
}

class Agency{
    ..property..
    information: Infomation
    product :
    transaction:
    billing:
    ..method..
}

class Admin{
    ..property..
    ..method..
    read()
    create()
    update()
    delete()
}

@enduml